-- MySQL Script generated by MySQL Workbench
-- 11/20/15 18:10:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema daw_recetas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `daw_recetas` ;

-- -----------------------------------------------------
-- Schema daw_recetas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `daw_recetas` DEFAULT CHARACTER SET utf8 ;
USE `daw_recetas` ;

-- -----------------------------------------------------
-- Table `daw_recetas`.`recetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw_recetas`.`recetas` ;

CREATE TABLE IF NOT EXISTS `daw_recetas`.`recetas` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NOT NULL,
  `descripcion` TEXT NULL,
  `tipo_plato` CHAR(1) NOT NULL COMMENT 'Tipo Plato E=Entrantes, 1=Primeros, 2=Segundos, P=Postres, ...',
  `dificultad` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1=Muy Facil,5=Muy Dificil.',
  `comensales` TINYINT(1) NOT NULL DEFAULT 4 COMMENT 'Numero de comensales para la receta.',
  `tiempo_elaboracion` SMALLINT(4) NOT NULL DEFAULT 0 COMMENT 'Tiempo en Minutos de elaboracion de la receta.',
  `valoracion` TINYINT(1) NOT NULL DEFAULT 3 COMMENT 'Valoracion de la receta: 1=Peor, 3=Buena, 5=Mejor.',
  `usuario_id` INT(12) UNSIGNED NULL DEFAULT 0 COMMENT 'Usuario que ha creado la receta o CERO si no existe (como si fuera NULL).',
  `aceptada` TINYINT(1) NULL COMMENT 'Indicador de receta aceptada o no.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daw_recetas`.`receta_pasos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw_recetas`.`receta_pasos` ;

CREATE TABLE IF NOT EXISTS `daw_recetas`.`receta_pasos` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  `receta_id` INT(12) UNSIGNED NOT NULL,
  `orden` TINYINT(2) NOT NULL DEFAULT 0,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daw_recetas`.`receta_paso_imagenes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw_recetas`.`receta_paso_imagenes` ;

CREATE TABLE IF NOT EXISTS `daw_recetas`.`receta_paso_imagenes` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  `receta_paso_id` INT(12) UNSIGNED NOT NULL,
  `orden` TINYINT(2) NOT NULL DEFAULT 0,
  `imagen` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daw_recetas`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw_recetas`.`categorias` ;

CREATE TABLE IF NOT EXISTS `daw_recetas`.`categorias` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NULL,
  `descripcion` TEXT NULL,
  `categoria_padre_id` INT(12) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Identificador de la categoria padre en caso de estar ordenados por jerarquías.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daw_recetas`.`receta_categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw_recetas`.`receta_categorias` ;

CREATE TABLE IF NOT EXISTS `daw_recetas`.`receta_categorias` (
  `receta_id` INT(12) UNSIGNED NOT NULL,
  `categoria_id` INT(12) UNSIGNED NOT NULL,
  INDEX `receta_categorias_receta_id_idx` (`receta_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daw_recetas`.`ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw_recetas`.`ingredientes` ;

CREATE TABLE IF NOT EXISTS `daw_recetas`.`ingredientes` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NULL,
  `descripcion` TEXT NULL,
  `datos_nutricion` TEXT NULL DEFAULT 0 COMMENT '(opcional) Datos nutricionales del ingrediente',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daw_recetas`.`receta_ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw_recetas`.`receta_ingredientes` ;

CREATE TABLE IF NOT EXISTS `daw_recetas`.`receta_ingredientes` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  `receta_id` INT(12) UNSIGNED NOT NULL,
  `ingrediente_id` INT(12) UNSIGNED NOT NULL,
  `cantidad` FLOAT NOT NULL DEFAULT 0,
  `medida` VARCHAR(45) NULL,
  `notas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daw_recetas`.`receta_comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw_recetas`.`receta_comentarios` ;

CREATE TABLE IF NOT EXISTS `daw_recetas`.`receta_comentarios` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  `receta_id` INT(12) UNSIGNED NOT NULL,
  `usuario_id` INT(12) UNSIGNED NOT NULL COMMENT 'Usuario que ha creado el comentario. No deberia ser CERO (como si fuera NULL).',
  `fechahora` DATETIME NOT NULL,
  `texto` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daw_recetas`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw_recetas`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `daw_recetas`.`usuarios` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL COMMENT 'Correo Electronico y \"login\" del usuario.',
  `password` VARCHAR(32) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `rol` CHAR(1) NOT NULL COMMENT 'Tipo de Perfil: C=Colaborador, A=Administrador, T=Tienda.',
  `aceptado` TINYINT(1) NOT NULL COMMENT 'Indicador de usuario aceptado su registro o no.',
  `creado` DATETIME NOT NULL COMMENT 'Fecha y Hora de creacion del usuario',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC));


-- -----------------------------------------------------
-- Table `daw_recetas`.`menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw_recetas`.`menus` ;

CREATE TABLE IF NOT EXISTS `daw_recetas`.`menus` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` TEXT NOT NULL,
  `descripcion` TEXT NOT NULL,
  `usuario_id` INT(12) UNSIGNED NULL COMMENT 'Usuario que ha creado el menu o CERO si no existe (como si fuera NULL).',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daw_recetas`.`menu_platos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw_recetas`.`menu_platos` ;

CREATE TABLE IF NOT EXISTS `daw_recetas`.`menu_platos` (
  `menu_id` INT(12) UNSIGNED NOT NULL,
  `receta_id` INT(12) UNSIGNED NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daw_recetas`.`planificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw_recetas`.`planificaciones` ;

CREATE TABLE IF NOT EXISTS `daw_recetas`.`planificaciones` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `periodo` VARCHAR(25) NOT NULL COMMENT 'Texto indicativo del Periodo de planificacion.',
  `usuario_id` INT(12) UNSIGNED NOT NULL COMMENT 'Usuario que ha creado la planificacion o CERO si no existe (como si fuera NULL).',
  `notas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daw_recetas`.`planificacion_menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw_recetas`.`planificacion_menus` ;

CREATE TABLE IF NOT EXISTS `daw_recetas`.`planificacion_menus` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  `planificacion_id` INT(12) UNSIGNED NOT NULL,
  `menu_id` INT(12) UNSIGNED NOT NULL COMMENT 'Menu relacionado con el dia planificado',
  `numero_dia` SMALLINT(3) NOT NULL COMMENT 'Numero de dia del menu dentro de la planificacion.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daw_recetas`.`tiendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw_recetas`.`tiendas` ;

CREATE TABLE IF NOT EXISTS `daw_recetas`.`tiendas` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `domicilio` VARCHAR(150) NULL,
  `poblacion` VARCHAR(50) NULL,
  `provincia` VARCHAR(50) NULL,
  `usuario_id` INT(12) UNSIGNED NOT NULL COMMENT 'Usuario que se corresponde con la tienda para poder conectar a la aplicación web.',
  `activa` TINYINT(1) NOT NULL COMMENT 'Si la tienda esta activa para conectar como usuario, y si estará visible desde el portal junto con sus ofertas independientemente de que esté visible o no.',
  `visible` TINYINT(1) NOT NULL COMMENT 'Si la tienda y sus ofertas estarán visibles en el portal aunque esté la tienda activa.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daw_recetas`.`tienda_ofertas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daw_recetas`.`tienda_ofertas` ;

CREATE TABLE IF NOT EXISTS `daw_recetas`.`tienda_ofertas` (
  `id` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tienda_id` INT(12) UNSIGNED NOT NULL,
  `ingrediente_id` INT(12) UNSIGNED NOT NULL,
  `descripcion` TEXT NULL,
  `envase` TEXT NULL,
  `cantidad` FLOAT NOT NULL DEFAULT 0,
  `medida` VARCHAR(45) NULL,
  `notas` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
